# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mazhuang.org
date_format: "ordinal"
title: èŠ±èŠ±ğŸ¯çš„åšå®¢
subtitle: 
description: "æˆ‘çš„ä¸ªäººåšå®¢"
keywords: huahuahu
favicon: /favicon.jpeg
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Tenghu Guo
organization: TME
organization_url: https://y.qq.com
github_username: huahuahu
location: ShenZhen, China
email: guotenghu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

  -
    href: /categories/
    label: åˆ†ç±»

  -
    href: /wiki/
    label: ç»´åŸº

  -
    href: /links/
    label: é“¾æ¥

  -
    href: /about/
    label: å…³äº

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: huahuahu/huahuahu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢è¿™äº›ä¿¡æ¯ä¸ºä½ è‡ªå·±ç”³è¯·çš„
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: mzlogin
# https://gentie.163.com
# netease_gentie:
#     productKey: 560ed243b708465d82d5a0a5f3b83da1
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: huahuahu
    repo: blog-comments
    oauth:
        client_id: c8da80f55f392fb7d2b1
        client_secret: 57293d5b105fe44dfeee77df7f778deb12aa7853
# åœ¨ä½¿ç”¨å…¶å®ƒè¯„è®ºç»„ä»¶æ—¶å¯ç‚¹å‡»æ˜¾ç¤º Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-101926689-1

